### PR TITLE
fix: Fix schema keys with special characters (#2)

### PR DESCRIPTION
**Pull request by wootwoot1234**

### CODE REVIEW

**Comment by wootwoot1234** [comment]
Copy of https://github.com/francescov1/mongoose-tsgen/pull/92 with the `String.raw${key};` change

**Comment by wootwoot1234** [comment]
@francescov1 what do you think?  Can you help me regenerate the `/helpers/tests/artifacts/*` files?

**Comment by wootwoot1234** [comment]
This solution didn't work for me but the `line += JSON.stringify(key);` from #92 did, I'm closing this for now.

**Comment by francescov1** [comment]
Thanks! Will move the chat over to the other PR

**Pull request closed without merging**
